### ISSUE TITLE
If the API weren't such crap, it wouldn't contribute complexity to this library

### ISSUE THREAD

**Issue by faddat** [svk31/graphenejs-lib#4]
I mean the bitshares API.  

Look, fix em, or.....

Well, don't.  

Does bitshares have documentation of the API calls?  I am trying to write a simple go app against bts.  Is it only inline docs like steem?  

You realize that this is way way more complex than it needs to be right?  Look, I can GENERATE the js for my APIS.....

https://app.swaggerhub.com/api/faddat/bbg/0.0.3

And then it is all neat-like.  This is the primary community frustration with graphene and it's growing not shirnking.  I'm not trying to throw a fuck you in your face, or harm the community with these comments, sir.  Code coming out of graphene-land takes 10x the effort to write against.

**Comment by svk31** [comment]
I realize it's complex, the main reason for that is that this library was extracted from the code used in graphene-ui, and as such it probably has way more stuff than it needs to, and 

I'm not sure what the issue is actually for but I guess you want me to rewrite the whole thing? Which part, the transaction signing or the websockets api? Because there's a separate library for that..

Or are you talking about the actual API offered by the witness_node?
