### ISSUE TITLE
Return value of ChainStore.getObject and ChainStore.getAsset when data is not in the cache

### ISSUE THREAD

**Issue by andriantolie** [svk31/graphenejs-lib#8]
Wouldn't it be nicer if Promise object is returned when ChainStore.getObject and ChainStore.getAsset find out that data is not in the cache and it is in the middle of fetching it from the blockchain? The current implementation returns 'undefined' which makes it harder to determine when the data arrives at the cache. Just a suggestion from the things that I observed when using the library :)

**Comment by svk31** [comment]
First off thanks for looking throught the code, it could use more eyes on it :)

The main ChainStore methods like getObject and getAsset are designed to be completely synchronous, that's why they don't return promises. In this case undefined means "I'm still fetching, the object might exist", and `null` means "I've looked and that object does not exist".

It's designed like this in order to play nicely with React's render cycles, and to be fire and forget. If you need promises you can use the FetchChain / FetchChainObjects methods.

**Comment by andriantolie** [comment]
I see, I understand the purpose of FetchChain / FetchChainObjects now.
When you mention it to play nicely with React's render cycles, how does the ChainStore bind together with React components? I mean how does ChainStore trigger React components to re-render when getObject finish fetching and storing it inside cache? Thanks!

**Comment by svk31** [comment]
So for that there's a HOC called BindToChainState that is used to resolve objects. An easy component to look at for an example is AssetName.jsx. It used to be a decorator but I refactored it slightly since Babel 6 didn't support decorators.

Basically we define a number of props using ChainTypes, and these props get resolved by the ChainStore and replaced with the actual object from the blockchain. In the case of AssetName, the object is an asset, so we set a proptype of ChainAsset:

```
static propTypes = {
		asset: ChainTypes.ChainAsset.isRequired,
...
}
```
We could've used ChainTypes.ChainObject also, but ChainAsset means that in BindToChainState the getAsset method will be used, which fetches some additional objects for each asset that are useful. There's also ChainAccount which works the same way. ChainAccount and ChainAsset also mean you can use names instead of object ids for the initial prop value, so AssetName can resolve a prop of "USD" to the corresponding object which has ID `1.3.121`.

BindToChainState also registers a subscription with the ChainStore, and updates its child component when the ChainStore publishes an update to its subscriptions. That happens whenever an object is changed in the ChainStore, so each component should use shouldComponentUpdate to check whether it actually needs to update.

**Comment by andriantolie** [comment]
I see. This makes things clearer to me. Thanks!
By the way, also in the same codebase as AssetName.jsx (cryptonomex/graphene), I saw some of the call to the blockchain is being done by using Apis.instance from graphenejs-ws directly. Will any call done by Apis.instance also trigger BindToChainState to update the cache? And is there any advantage of using Apis.instance directly instead of using ChainStore? It seems strange that the codebase is mixing the usage of Apis.instance and ChainStore to achieve the same things, i.e. getAsset.
